//generated by genheader.sh write by wangbin
/********************************************************
**libezxaid.so.1.0.0
**2010年 06月 24日 星期四 17:07:01 CST
**libraries depends:
	ezxaid,ezxam,dmnative,ezxphone,ezx-cmseccert,ezxdrmsp,ezxssl,ezxtapi,ezxflex,ezxdrmsecuretime,ezxdrmcipher
*************************************************************/
#ifndef AM_JAVAPACKAGEMANAGER_H
#define AM_JAVAPACKAGEMANAGER_H

#include <AM_Global.h>
class AM_AppLnk;

class ZConfig;

class AM_JavaPackageManager
{
public:
	enum JPM_INSTALL_FLAG { Flag1, Flag2 };
	
	void getSuiteName(QString const&, QString const&, QString&);
	void updateConfig(ZConfig*, QString, QString, QString, int, bool, bool);
	void clearPreloadJava();
	void writeConfigEntry(ZConfig*, AM_JavaPackageManager::JPM_INSTALL_FLAG, AM_Global::Device, QString&, QString, QString, QString, int, int, int, bool, bool, int, int, int);
	void notifyAmRMInstall(AM_Global::Device, QString const&, QString const&, bool);
	void selectDeviceGroup(QString const&, int, AM_Global::Device&, QString&);
	void notifyAmRMUninstall(QString const&, QString const&);
	void getInstalledJavaInfo(int, AM_Global::Device&, QString&, QString&, QString&);
	void install(QString const&, QString const&);
	void install(QString const&, QString const&, QString const&, QString const&, QList<int>&, QList<QString>&, int&, QList<QString>&, QString&, int&);
	void install(QString const&, QString const&, QString const&, QString const&, int&, QString&, int&, QList<QString>&);
	void install(QString const&, QString const&, QString const&, QString const&, int&, QString&, int&, QList<QString>&, QString&, int&);
	void preload(QString const&, QString const&, AM_Global::Device, QString const&, int);
	void uninstall(AM_AppLnk const&, bool);
	void uninstall(int, bool, unsigned int);
	AM_JavaPackageManager();
	~AM_JavaPackageManager();
	
private:
	char x[65];
	
};

#endif //AM_JAVAPACKAGEMANAGER_H

