//generated by genheader.sh write by wangbin

#ifndef QTESTCAPTUREHANDLER_H
#define QTESTCAPTUREHANDLER_H

class QTestCaptureHandler :public QObject
{
public:
	QTestCaptureHandler(void);
	~QTestCaptureHandler();
	
};

#endif //QTESTCAPTUREHANDLER_H

