//generated by genheader.sh write by wangbin

#ifndef UTIL_ANIMWIDGET_H
#define UTIL_ANIMWIDGET_H

class UTIL_AnimWidget :public QWidget
{
	Q_OBJECT
public:
	UTIL_AnimWidget(QWidget *parent=0,char  const* name=0);
	
	void start(int);
	
public slots:
	void reset();
	void stop();
	
protected:
	virtual void paintEvent(QPaintEvent *);
signals:
	void timeout();
	
};

#endif //UTIL_ANIMWIDGET_H

