//generated by genheader.sh write by wangbin
/********************************************************
**libezxappbase.so.1.0.0
**Tue Aug 24 10:23:15     2010
*************************************************************/
#ifndef UTIL_TIMECONVERSION_H
#define UTIL_TIMECONVERSION_H
#include <qdatetime.h>
class UTIL_TimeConversion
{
public:
	QDateTime fromISO8601(QCString const&);
	bool isSpanDstRule(QString const&, QDateTime const&);
	long toUTC(QDateTime const&);
	QDateTime fromUTC(long);
	QDate toISO8601(QDate const&);
	QDateTime toISO8601(QDateTime const&);
	
};

#endif //UTIL_TIMECONVERSION_H

