//generated by genheader.sh write by wangbin
/********************************************************
**libezxappbase.so.1.0.0
**Tue Aug 24 10:20:15     2010
*************************************************************/
#ifndef IM_RESDIR
#define IM_RESDIR

class IM_ResDir
{
public:
	static QString getIMPluginDir(int);
	
};

#endif //IM_RESDIR

