//generated by genheader.sh write by wangbin
/********************************************************
**libezxappbase.so.1.0.0
**Tue Aug 24 10:22:44     2010
*************************************************************/
#ifndef UTIL_PRIORITIZEDDIALOG_H
#define UTIL_PRIORITIZEDDIALOG_H
#include <UTIL_Dialog.h>

class UTIL_PrioritizedDialogData;

class UTIL_PrioritizedDialog : UTIL_Dialog
{
	Q_OBJECT
public:
	UTIL_PrioritizedDialog(int, UTIL_Dialog::DialogType dt=UTIL_Dialog::DTMiddleSize, bool title=1, \
							QWidget* parent=0, char const* name=0, int modal=0, unsigned int flag=0);
	~UTIL_PrioritizedDialog();
	bool isPriorityAvailable();
	int dialogResult();
	
signals:
	void sigPriorityInterrupted();
	
public slots:
	void dialogExec();
	void dialogShow();
	void slotDialogInterrupt();

protected:
	virtual void event(QEvent*);
	virtual void hideEvent(QHideEvent*);
	virtual void closeEvent(QCloseEvent*);
	
private:
	void init();
	
	UTIL_PrioritizedDialogData *d;
	
};

#endif //UTIL_PRIORITIZEDDIALOG_H

