//generated by genheader.sh write by wangbin
/********************************************************
**libezxaid.so.1.0.0
**2010年 06月 24日 星期四 17:07:01 CST
*************************************************************/
//--------------------------------------------------------------------------------------------------
//                                                                               
//
//                            Motorola Confidential Proprietary
//                   Template ID and version: IL93-TMP-01-0107  Version 1.10
//                    (c) Copyright Motorola XXXX-XXXX, All Rights Reserved
//   
//
// Revision History:
//                             Modification     Tracking
// Author (core ID)                Date          Number     Description of Changes
// -------------------------   ------------    ----------   ----------------------------------------
// Developer Name/ID            MM/DD/YYYY     CSGceXXXXX   BRIEF description of changes made   
//
// Tim Zhao/w19411		6/25/2002			created first time
//
//
//--------------------------------------------------------------------------------------------------

#ifndef __AM_PACKAGEMANAGER_H__
#define __AM_PACKAGEMANAGER_H__

#include "AM_Global.h"
//#include "AM_AppLink.h"
//#include "AM_GroupLink.h"

#include <qobject.h>
#include <quuid.h>

#define AM_REGISTRY_MANAGER_CHANNEL         "AM/RegistryiMgr/Channel"
#define AM_REGISTRY_UNINSTALL_APP           "UninstallApp(QString)"
#define AM_REGISTRY_INSTALL_APP             "InstallApp(int, QString, QString, int)"

class AM_PackageManager : public QObject
{
public:
    AM_PackageManager(QObject * parent = 0, const char * name=0);
    virtual ~AM_PackageManager();
#if 0
    static bool changeGroup( const int appUid, const int groupUid );
    static bool changeOrder( const QArray<int> &orders, AM_GroupLink::Groups group );
#endif
    // subject to change to QUuid::createQUuid().
    QUuid createUuid() const;

    // add an application to main menu, so that it can be displayed.
    // appUid: group name( inside the [] ) in SysRegistry or other databases.
    // folderUid: the desdination folder the app will be added to.
    // index: the position on main menu.
    bool addAppToMainMenu( const QString &appUid, const QString &folderUid, int index = -1 );
    
protected:
    bool cleanInstallTmpDir( void );
    static int  statusSystem( const char *cmd );
    AM_Global::Device getDevice( void ) const { return device; }; /Exists in E6?
    void setDevice( AM_Global::Device device_ ) { device = device_; };

    bool checkDeviceSpace( const QString &pkgFile ) const;
    bool unpackage( const QString &pkgFile );
    QString getPackageDirName( void );
    void notifyUpdateHomeViews( void );
    QString getInstallDate( void );

#if 0
    void getNewInstalledAppPositions( const int groupUid, int &position, int &allPosition );
    QString locateNewPackageDir( const QString &packageDirName, const QString &targetRootDirName );
    bool moveToNewLocation( void );
    void deleteAppRecords( const int uid );
#endif

private:
    QString packageDirName;
    QString packageFilePath;

    AM_Global::Device device;

    //
    // disable copy construct and operator =
    // this will disable all the derived classes which inherit from this class.
    //
    AM_PackageManager( const AM_PackageManager & );
    AM_PackageManager & operator = ( const AM_PackageManager & );
};

#endif //__AM_PACKAGEMANAGER_H__
