//generated by genheader.sh write by wangbin
/********************************************************
**libezxam.so.1.0.0
**2010年 05月 03日 星期一 18:11:58 CST
*************************************************************/
#ifndef AM_EMBEDDEDLINK_H
#define AM_EMBEDDEDLINK_H
#include <AM_AppObject.h>
//class AM_LauncherInterface;

class AM_EmbeddedLink : public AM_AppObject
{
public:
	AM_EmbeddedLink();
	virtual ~AM_EmbeddedLink();
	
	virtual AM_RESULT_CODE_T createObject(QMap<QString, QString> const&);
	virtual AM_RESULT_CODE_T getInvisiblNetLinkFromDmt(QString*, QString*);
	virtual AM_RESULT_CODE_T dump();
	virtual AM_RESULT_CODE_T invoke(AM_LauncherInterface const&);
	
private:
	
};

#endif //AM_EMBEDDEDLINK_H

