//generated by genheader.sh write by wangbin
/********************************************************
**libezxam.so.1.0.0
**2010年 05月 03日 星期一 18:11:58 CST
*************************************************************/
#ifndef AM_GROUPLISTSCROLLVIEW_H
#define AM_GROUPLISTSCROLLVIEW_H

#include <qlistview.h>

class AM_GroupListScrollViewItem :public QListViewItem
{
	Q_OBJECT
public:
	AM_GroupListScrollViewItem(QString, QListView* parent, QString const&, QCheckListItem::Type=QCheckListItem::CheckBox);
	virtual ~AM_GroupListScrollViewItem();
	
private:
			
};

class AM_Folder;

class AM_GroupListScrollView :public QListView
{
	Q_OBJECT
public:
	AM_GroupListScrollView(QList<AM_Folder>, QString, QWidget* parent=0);
	virtual ~AM_GroupListScrollView();
	
	QString getSelectedGroup();	
	
public slots:
	void slotClicked(QListViewItem*);
	
private:
			
};

#endif //AM_GROUPLISTSCROLLVIEW_H

