//generated by genheader.sh write by wangbin
/********************************************************
**libezxam.so.1.0.0
**2010年 05月 03日 星期一 18:11:58 CST
*************************************************************/
#ifndef AM_MAINMENUINTERFACE_H
#define AM_MAINMENUINTERFACE_H

class AM_MainMenuInterface
{
public:
	AM_MainMenuInterface();
	~AM_MainMenuInterface();
	
	void ShowMainMenu();
	
private:
	
};

#endif //AM_MAINMENUINTERFACE_H

