//generated by genheader.sh write by wangbin
/********************************************************
**libezxam.so.1.0.0
**2010年 05月 03日 星期一 18:11:59 CST
*************************************************************/
#ifndef AM_STANDARDDLG_H
#define AM_STANDARDDLG_H
#include <UTIL_Dialog.h>
class QLayout;

class AM_StandardDlg :public UTIL_Dialog
{
	Q_OBJECT
public:
	AM_StandardDlg(QWidget* parent=0, char const* name=0);
	virtual ~AM_StandardDlg();
	
	QLayout* getMainLayout();
	void init();
	
	void preInit();
	void postInit();
	int getSelect();
	
public slots:
	void slotOk();
	void slotCancel();
	
private:
	QLayout* mainLayout;
	char x[256];	
	
};

#endif //AM_STANDARDDLG_H

