//generated by genheader.sh write by wangbin
/********************************************************
**libezxam.so.1.0.0
**2010年 05月 03日 星期一 18:11:59 CST
*************************************************************/
#ifndef AM_SYSTEMCONFIG_H
#define AM_SYSTEMCONFIG_H

class AM_SystemConfig
{
public:
	AM_SystemConfig();
	~AM_SystemConfig();
	
	QString DRMUid();
	QString ezxGid();
	QString ezxUid();
	
private:
	QString m_drmuid, m_ezxuid, m_ezxgid;		
};

#endif //AM_SYSTEMCONFIG_H

