//generated by genheader.sh write by wangbin

#ifndef UTIL_ANIMWIDGET_H
#define UTIL_ANIMWIDGET_H

class UTIL_AnimWidget :public QWidget
{
public:
	UTIL_AnimWidget(QWidget *parent=0,char  const* name=0);
	
	void reset(void);
	void start(int);
	void stop(void);
	
protected:
	void paintEvent(QPaintEvent *);
signals:
	void timeout(void);
	
};

#endif //UTIL_ANIMWIDGET_H

