//generated by genheader.sh write by wangbin
/********************************************************
**libezxaddrbk.so.1.0.0
**2010年 05月 01日 星期六 12:31:04 CST
*************************************************************/
#ifndef ADDRBK_CON_LISTVIEW_H
#define ADDRBK_CON_LISTVIEW_H

class ADDRBK_CON_ListViewPrivate::ItemColumnInfo
{
public:
	void ~ItemColumnInfo();
	
};

class ADDRBK_CON_ListViewPrivate::ViewColumnInfo
{
public:
	void ~ViewColumnInfo();
	
};

class ADDRBK_CON_ListViewPrivate::Root
{
public:
	void invalidateHeight();
	void setup();
	void setHeight(int);
	void Root(ADDRBK_CON_ListView*);
	void ~Root();
	void theListView();
	
};

class ADDRBK_CON_ListViewPrivate::ItemColumnInfo
{
public:
	void ~ItemColumnInfo();
	
};

class ADDRBK_CON_ListView :public QListView
{
public:
	ADDRBK_CON_ListView(QWidget*, char const*);
	ADDRBK_CON_ListView(QWidget*, char const*, unsigned int);
	~ADDRBK_CON_ListView();
	
	void insertItem(ADDRBK_UI_ListViewItem*);
	void onViewport();
	void removeItem(ADDRBK_UI_ListViewItem*);
	void setPalette(QPalette const&);
	void setSorting(int, bool);
	void eventFilter(QObject*, QEvent*);
	void makeVisible();

	void selectRange(ADDRBK_UI_ListViewItem*, ADDRBK_UI_ListViewItem*, bool, bool, bool);
	void setSelected(ADDRBK_UI_ListViewItem*, bool);
	void styleChange(QStyle&);
	void doAutoScroll();

	void removeColumn(int);

	void doubleClicked(ADDRBK_UI_ListViewItem*);
	void enabledChange(bool);


	void setColumnText(int, QString const&);
	void setColumnText(int, QIconSet const&, QString const&);
	void setItemMargin(int);
	void triggerUpdate();
	void clearSelection();


	void setColumnWidth(int, int);
	void setContentsPos(int, int);
	void setCurrentItem(ADDRBK_UI_ListViewItem*);
	void updateContents();
	void invertSelection();
	void setTreeStepSize(int);
	void changeSortColumn(int);
	void handleItemChange(ADDRBK_UI_ListViewItem*, bool, bool);
	void handleSizeChange(int, int, int);
	void reconfigureItems();
	void selectionChanged(ADDRBK_UI_ListViewItem*);
	void selectionChanged();
	void setSelectionMode(ADDRBK_CON_ListView::SelectionMode);
	void updateDirtyItems();
	void updateGeometries();
	void ensureItemVisible(ADDRBK_UI_ListViewItem const*);
	void setMultiSelection(bool);



	void setColumnAlignment(int, int);
	void setColumnWidthMode(int, ADDRBK_CON_ListView::WidthMode);
	void setRootIsDecorated(bool);
	void setShowSortIndicator(bool);

	void setAllColumnsShowFocus(bool);

	void init();
	void show();
	void sort();
	void clear();

	void setFont(QFont const&);
	void setOpen(ADDRBK_UI_ListViewItem*, bool);
	void expanded(ADDRBK_UI_ListViewItem*);
	void takeItem(ADDRBK_UI_ListViewItem*);
	void addColumn(QString const&, int);
	void addColumn(QIconSet const&, QString const&, int);
	void collapsed(ADDRBK_UI_ListViewItem*);
	void selectAll(bool);
	void showEvent(QShowEvent*);

	void childCount();
	void columnText(int);
	void firstChild();
	bool isSelected(ADDRBK_UI_ListViewItem const*);
	void itemMargin();
	void columnWidth(int);
	void currentItem();

	void selectedItem();
	void treeStepSize();
	void selectionMode();
	int columnAlignment(int);
	int columnWidthMode(int);
	QSize minimumSizeHint();
	void rootIsDecorated();
	void isMultiSelection();
	void buildDrawableList();
	void showSortIndicator();
	void allColumnsShowFocus();
	QHeader* header();
	bool isOpen(ADDRBK_UI_ListViewItem const*);
	ADDRBK_UI_ListViewItem* itemAt(QPoint const&);
	int columns();
	QRect itemRect(ADDRBK_UI_ListViewItem const*);

	
signals:
	void onItem(ADDRBK_UI_ListViewItem*);
	void clicked(ADDRBK_UI_ListViewItem*);
	void clicked(ADDRBK_UI_ListViewItem*, QPoint const&, int);
	void itemPos(ADDRBK_UI_ListViewItem const*);
	void pressed(ADDRBK_UI_ListViewItem*);
	void pressed(ADDRBK_UI_ListViewItem*, QPoint const&, int);
	void rightButtonClicked(ADDRBK_UI_ListViewItem*, QPoint const&, int);
	void rightButtonPressed(ADDRBK_UI_ListViewItem*, QPoint const&, int);
	void mouseButtonClicked(int, ADDRBK_UI_ListViewItem*, QPoint const&, int);
	void mouseButtonPressed(int, ADDRBK_UI_ListViewItem*, QPoint const&, int);
	void returnPressed(ADDRBK_UI_ListViewItem*);
	void currentChanged(ADDRBK_UI_ListViewItem*);
	void widthChanged(ADDRBK_UI_ListViewItem const*, int);
				
protected:
	QSize sizeHint() const;	
	void repaintItem(ADDRBK_UI_ListViewItem const*);
	void contentsMousePressEvent(QMouseEvent*);
	void contentsMouseReleaseEvent(QMouseEvent*);
	void contentsMouseDoubleClickEvent(QMouseEvent*);	
	void contentsMouseMoveEvent(QMouseEvent*);
	void paintEmptyArea(QPainter*, QRect const&);
	void focusOutEvent(QFocusEvent*);
	void keyPressEvent(QKeyEvent*);	
	void drawContentsOffset(QPainter*, int, int, int, int, int, int);	
	void focusInEvent(QFocusEvent*);
	void resizeEvent(QResizeEvent*);
			
};

#endif //ADDRBK_CON_LISTVIEW_H

