//generated by genheader.sh write by wangbin
/********************************************************
**libezxshare.so.1.0.0
**2010年 04月 07日 星期三 16:36:22 CST
*************************************************************/
#ifndef SHARE_METHODDLG_H
#define SHARE_METHODDLG_H

class SHARE_MethodDlg
{
public:
	void selectMethod(int, bool);
	void method();
	SHARE_MethodDlg(int, QWidget*, char const*, bool);
	~SHARE_MethodDlg();
	
};

#endif //SHARE_METHODDLG_H

