//generated by genheader.sh write by wangbin
/********************************************************
**libezxcalendarengine.so.1.0.0
**2010年 04月 17日 星期六 13:52:08 CST
*************************************************************/
#ifndef ZCALENDAREVENTLIST_H
#define ZCALENDAREVENTLIST_H

class ZCalendarEventList
{
public:
	void removeEvent(QString&);
	void updateEvent(ZCalendarEvent&);
	void exportVCalendar(ZCalendarEvent&, QArray<char>&);
	void importVCalendar(QArray<char>&, ZCalendarEvent&);
	void itemsByCategory(QString&, QValueList<ZCalendarEvent>&);
	void getLocalTimeZone(ZCalendarTimeZone_T&);
	void items(ZCalendarSearchType_T, long&, long&, bool, QValueList<ZCalendarEvent>&);
	void items(QValueList<ZCalendarEvent>&);
	void items(ZCalendarEvent const&, QValueList<ZCalendarEvent>&);
	void items(QString const&, QValueList<ZCalendarEvent>&);
	void toUTC(QDateTime&, ZCalendarTimeZone_T&, long&);
	void fromUTC(long, ZCalendarTimeZone_T&, QDateTime&);
	void addEvent(ZCalendarEvent&);
	void getEvent(QString, ZCalendarEvent&);
	ZCalendarEventList();
	~ZCalendarEventList();
	
};

#endif //ZCALENDAREVENTLIST_H

