//generated by genheader.sh write by wangbin
/********************************************************
**libezxaddrbk.so.1.0.0
**2010年 05月 01日 星期六 12:31:04 CST
*************************************************************/
#ifndef ADDRBK_CHALLSORTDLG_H
#define ADDRBK_CHALLSORTDLG_H

#include <ZBaseDialog.h>
class ADDRBK_UI_ListViewItem;

class ADDRBK_ChAllSortDlg :public ZBaseDialog
{
public:
	void checkSelectAll(ADDRBK_UI_ListViewItem*);
	void setCheckedItem(ADDRBK_UI_ListViewItem*);
	//void existInCheckItems(ADDRBK_CheckedData const&);
	void selectAll(bool);
	ADDRBK_ChAllSortDlg(QWidget* parent=0, char const* name=0, bool x=true, unsigned int flag=0);
	~ADDRBK_ChAllSortDlg();
private:
	char a[256];	
};

#endif //ADDRBK_CHALLSORTDLG_H

