//generated by genheader.sh write by wangbin
//libezxbluetooth libezxmbtapi

#ifndef BT_UI_COMMONDLG_H
#define BT_UI_COMMONDLG_H

#include <UTIL_Dialog.h>

class BT_UI_CommonDLG :public UTIL_Dialog
{
public:
	BT_UI_CommonDLG(UTIL_Dialog::DialogType dt=UTIL_Dialog::DTLargeSize, bool dlgtitle=true);
	~BT_UI_CommonDLG();
	
	void createLabel(QWidget* parent, QString title, int, int, int, int);
	void createTitle(QString, QWidget*);
	void createOneBtn(QString btnStr, QWidget*);
	void createListView(QString, QWidget*);
	void create1stOfTwoBtn(QString, QWidget*);
	void create2ndOfTwoBtn(QString, QWidget*);
	void createProgressBar(QWidget*, int, int, int, int, int);
	void createMultiLineEdit(QWidget*, QString, int, int, int, int);
	void createTitleWithAllCheckBox(QString, QString, QWidget*);
	
	
};

#endif //BT_UI_COMMONDLG_H

