//generated by genheader.sh write by wangbin
/********************************************************
**libezxshare.so.1.0.0
**2010年 04月 07日 星期三 16:36:22 CST
*************************************************************/
#ifndef SHARE_TOOL_H
#define SHARE_TOOL_H

class SHARE_Tool
{
public:
	void saveObject(QString const&, QArray<char> const&, int, int);
	void shareByIrda(SHARE_Tool::OBJECT_INFO const&, QArray<char> const&);
	void shareByIrda(SHARE_Tool::OBJECT_INFO const&, QString const&, bool);
	void selectMethod(int, bool);
	void shareByBtIrda(SHARE_Tool::SHARE_METHOD, QValueList<SHARE_Tool::SHARE_OBJECT> const&);
	void genTmpFileName(SHARE_Tool::SHARE_METHOD, QString const&, QString const&);
	void shareByBt(QValueList<SHARE_Tool::OBJECT_INFO> const&, QArray<char> const&, QValueList<int> const&);
	void shareByBt(QValueList<SHARE_Tool::SHARE_OBJECT> const&);
	void shareByBt(SHARE_Tool::OBJECT_INFO const&, QArray<char> const&);
	void shareByBt(SHARE_Tool::OBJECT_INFO const&, QString const&, bool);
	
};

#endif //SHARE_TOOL_H

