//generated by genheader.sh write by wangbin
/********************************************************
**libezxappbase.so.1.0.0
**Tue Aug 24 10:22:30     2010
*************************************************************/
#ifndef UTIL_LAYOUT_H
#define UTIL_LAYOUT_H
#include <qlayout.h>

class UTIL_Layout :public QLayout
{
public:
	void setFormCSTLayout(QWidget*, QWidget*, UTIL_Layout::CST_TYPE);
	void setFormCSTLayout(QWidget*, QWidget*, QWidget*, UTIL_Layout::CST_TYPE);
	void setFormCSTLayout(QWidget*, QWidget*, QWidget*, QWidget*, UTIL_Layout::CST_TYPE);
	void setFormCSTLayout(QWidget*, QWidget*, QWidget*, QWidget*, QWidget*, UTIL_Layout::CST_TYPE);
	bool isFitAvatarPixmap(QString const&);
	void setFormItemLayout(QWidget*, QWidget*, UTIL_Layout::FORM_ITEM_TYPE);
	void setDialogCSTLayout(QWidget*, QWidget*, UTIL_Layout::CST_TYPE);
	void setDialogCSTLayout(QWidget*, QWidget*, QWidget*, UTIL_Layout::CST_TYPE);
	void setDialogCSTLayout(QWidget*, QWidget*, QWidget*, QWidget*, UTIL_Layout::CST_TYPE);
	void setDialogItemLayout(QWidget*, QWidget*, UTIL_Layout::DIALOG_ITEM_TYPE);
	void setCstWidgetGeometry(QWidget*, QWidget*, QRect const&);
	UTIL_Layout();
	~UTIL_Layout();
	
};

#endif //

