//generated by genheader.sh write by wangbin
/********************************************************
**libezxappbase.so.1.0.0
**Tue Aug 24 10:22:14     2010
*************************************************************/
#ifndef UTIL_IMAGEPARSER_H
#define UTIL_IMAGEPARSER_H
#include <qimage.h>
#include <qobject.h>
class UTIL_ImageParser :public QObject //??
{
	Q_OBJECT
public:
	UTIL_ImageParser(QByteArry, char const* name=0);
	UTIL_ImageParser(QString const& file, char const* name=0);
	~UTIL_ImageParser();
	QImage parse_bmp_image();
	QImage parse_gif_image();
	QImage parse_pbm_image();
	QImage parse_png_image();
	QImage parse_xbm_image();
	QImage parse_xpm_image();
	QImage parse_jpeg_image();
	QImage parse_wbmp_image();
	QImage parse(char const*);
};

#endif //UTIL_IMAGEPARSER_H

