//generated by genheader.sh write by wangbin
/********************************************************
**libezxappbase.so.1.0.0
**Tue Aug 24 10:22:02     2010
*************************************************************/
#ifndef UTIL_GIFPARSER_H
#define UTIL_GIFPARSER_H

class UTIL_GifParser
{
public:
	void parse();
	UTIL_GifParser(QArray<char>, bool);
	UTIL_GifParser(QString const&, bool);
	UTIL_GifParser(QArray<char>, bool);
	UTIL_GifParser(QString const&, bool);
	~UTIL_GifParser();
	
};

#endif //UTIL_GIFPARSER_H

