//generated by genheader.sh write by wangbin
/********************************************************
**libezxappbase.so.1.0.0
**Tue Aug 24 10:22:23     2010
*************************************************************/
#ifndef 
#define 

class UTIL_KeyboardLockClient
{
public:
	void disConnect();
	void sendCommand(UTIL_KeyboardLockCommand const*);
	void lockKeyboard();
	void removeInstance();
	void unlockKeyboard();
	void connectToServer();
	void resetLockRequest();
	void requestRelockKeyboard();
	void requestUnlockKeyboard();
	void instance();
	
};

#endif //

