//generated by genheader.sh write by wangbin
/********************************************************
**libezxappbase.so.1.0.0
**Tue Aug 24 10:22:03     2010
*************************************************************/
#ifndef UTIL_GIFPLAYER_H
#define UTIL_GIFPLAYER_H
#include <qlabel.h>
class UTIL_GifPlayer :public QLabel
{
	Q_OBJECT
public:
	UTIL_GifPlayer(QWidget*, char const*);
	UTIL_GifPlayer(QString const&);
	UTIL_GifPlayer(QString const&, QWidget*, char const*);
	UTIL_GifPlayer();
	~UTIL_GifPlayer();
	
	void decodeMore();
	void displayOne(int frame);
	void disableAlpha();
	void disableLooping();
	void setLooping(int);
	void setFramePeriod(int);
	void setMemoryLimit(int);
	void start(QString const& file, bool);
	void setSize(int width, int height);
	int status();
	bool playing();
	void setMinPeriod(int);
	
signals:
	void changed(QRect const&);
	void finished();
	void frameDone();
	void frameDone(QPoint const&, QRect const&);

public slots:
	virtual void end();
	void pushUpdate();
	void showNextFrame();
	void restart(bool);
	virtual void startshow();
	void terminate();
	
protected:
	void timerEvent(QTimerEvent*);
	void paintEvent(QPaintEvent*);
	QSize sizeHint() const;
	
	void decodeOne();
	
private:
	int _status;
	int _looping, _memLimit, _width, _height, _framePeriod, _minPeriod;
	
};

#endif //UTIL_GIFPLAYER_H

