//generated by genheader.sh write by wangbin
/********************************************************
**libezxappbase.so.1.0.0
**Tue Aug 24 10:22:11     2010
*************************************************************/
#ifndef UTIL_IP_VALIDATOR_H
#define UTIL_IP_VALIDATOR_H
#include <qvalidator.h>
class UTIL_IP_Validator :public QValidator
{
	Q_OBJECT
public:
	UTIL_IP_Validator(QWidget* parent);
	~UTIL_IP_Validator();

protected:
	virtual State validate( QString &, int & ) const;	
};

#endif //UTIL_IP_VALIDATOR_H

