//generated by genheader.sh write by wangbin
/********************************************************
**libezxappbase.so.1.0.0
**Tue Aug 24 10:22:20     2010
*************************************************************/
#ifndef UTIL_KEYTOUCHPANELEVENT_H
#define UTIL_KEYTOUCHPANELEVENT_H
#include <qobject.h>
class UTIL_KeyTouchPanelEvent :public QObject
{
	Q_OBJECT
public:
	UTIL_KeyTouchPanelEvent();
	~UTIL_KeyTouchPanelEvent();
	static UTIL_KeyTouchPanelEvent* instance();

public slots:	
	void slotTimeoutUI();
	void slotResetTimer();
	void slotActivateFunction();
		
};

#endif //UTIL_KEYTOUCHPANELEVENT_H

