//generated by genheader.sh write by wangbin
/********************************************************
**libezxappbase.so.1.0.0
**Tue Aug 24 10:23:09     2010
*************************************************************/
#ifndef UTIL_TAPI_DEVICE_H
#define UTIL_TAPI_DEVICE_H

#include <qobject.h>
class UTIL_TAPI_Event;

class UTIL_TAPI_Device :public QObject
{
	Q_OBJECT
public:
	UTIL_TAPI_Device(QObject*, char const*);
	~UTIL_TAPI_Device();
	
	bool IsTapiInvalid();

signals:
	void TapiDeviceClosed();

public slots:
	void CloseDevice();
	void TAPI_DeviceRead();
	bool ActivateTapiDevice(int);
	void setSocket(int);
	
protected:
	void TAPI_SendEvent(UTIL_TAPI_Event*);
	void event(QEvent*);
	
};

#endif //UTIL_TAPI_DEVICE_H

