//generated by genheader.sh write by wangbin
/********************************************************
**libezxappbase.so.1.0.0
**Tue Aug 24 10:21:54     2010
*************************************************************/
#ifndef UTIL_DIRECTPIXMAP_H
#define UTIL_DIRECTPIXMAP_H
#include <ZDirectPixmap.h>

class UTIL_DirectPixmap :public ZDirectPixmap
{
public:
	~UTIL_DirectPixmap();
	void rawCopy(bool rc=true);
	
};

#endif //UTIL_DIRECTPIXMAP_H

