//generated by genheader.sh write by wangbin

#ifndef UTIL_FACTORY_H
#define UTIL_FACTORY_H

class UTIL_PushButton;
class QComboBox;
class QLineEdit;
class ZMultiLineEdit;

class UTIL_Factory
{
public:
	UTIL_Factory(void);
	UTIL_PushButton *cstBackButton(QWidget *,char  const*);
	UTIL_PushButton *cstButton(QString  const&,QWidget *,UTIL_Factory::CST_BUTTON_POS_T);
	UTIL_PushButton *cstButton(QWidget *,UTIL_Factory::CST_BUTTON_POS_T);
	UTIL_PushButton *cstDisableMenuButton(QWidget *,char  const*);
	UTIL_PushButton *cstExitButton(QWidget *,UTIL_Factory::CST_BUTTON_POS_T,char  const*);
	UTIL_PushButton *cstMenuButton(QWidget *,char  const*);
	UTIL_PushButton *cstNewButton(QWidget *,char  const*);
	UTIL_PushButton *cstSlideHideButton(QWidget *,char  const*);
	UTIL_PushButton *dnlButton(QString  const&,QWidget *,char  const*);
	UTIL_PushButton *dnlButton(QWidget *,char  const*);
	QComboBox *formComboBox(QWidget *,char  const*);
	QLineEdit* formLineEdit(QWidget *,char  const*);
	ZMultiLineEdit* formMultiLineEdit(QWidget *,char  const*);
	~UTIL_Factory();

private:
	
};

#endif //UTIL_FACTORY_H

