//generated by genheader.sh write by wangbin
/*
	libezxqtnapi

*/

#ifndef ZPROFILESELECTDLG_H
#define ZPROFILESELECTDLG_H

class ZProfileSelectDlg
{
public:
	void selectedProfile(QString&);
	void slotOKBtnClicked();
	ZProfileSelectDlg(QStringList&, QString, QWidget*, char const*);
	~ZProfileSelectDlg();
	
};

#endif //ZPROFILESELECTDLG_H

