//generated by genheader.sh write by wangbin
/********************************************************
**libezxappsdk.so.1.0.0
**2010年 07月 07日 星期三 10:44:16 CST
*************************************************************/
#ifndef ZRESIZEDLG_H
#define ZRESIZEDLG_H
#include <UTIL_Dialog.h>

class ZResizeDlg :public UTIL_Dialog
{
public:
	ZResizeDlg(QWidget*, int, QArray<char>, char const*, char const*);
	virtual ~ZResizeDlg();
	
	void CanLoadImage(char const*);
	char** data();
	int exec();
};

#endif //ZRESIZEDLG_H

