//generated by genheader.sh write by wangbin
/*
	libezxqtnapi

*/
#ifndef ZSTATEDIALOG_H
#define ZSTATEDIALOG_H

class ZStateDialog
{
public:
	void setStateString(QString const&);
	ZStateDialog(QWidget*);
	~ZStateDialog();
	
};

#endif //ZSTATEDIALOG_H

