//generated by genheader.sh write by wangbin
//libam.so

#ifndef AM_POWEROFF_H
#define AM_POWEROFF_H

class AM_PowerOff
{
public:
	AM_PowerOff(void); 
	~AM_PowerOff();
	
	static void powerOff(void);
	static bool suspend(void);
	
public slots:
	void slotDatabaseDump(void);	
	void slotNotifyPmMasterReset(void);
	void slotNotifyPmTcmdMasterClear(void);
	void slotNotifyPmMasterClear(void);
	void slotNotifyPmPowerOff(void);
	void slotNotifyPmTcmdMasterReset(void);
	void slotTcmdMasterReset(void);
	void slotMasterReset(void);
	void slotMasterClear(void);
	void slotTcmdMasterClear(void);
	
};

#endif //AM_POWEROFF_H

