//generated by genheader.sh write by wangbin
/********************************************************
**libezxaid.so.1.0.0
**2010年 06月 24日 星期四 17:07:01 CST
**libraries depends:
	ezxaid,ezxam,dmnative,ezxphone,ezx-cmseccert,ezxdrmsp,ezxssl,ezxtapi,ezxflex,ezxdrmsecuretime,ezxdrmcipher
*************************************************************/

#ifndef AM_QTPACKAGEMANAGER_H
#define AM_QTPACKAGEMANAGER_H
#include <AM_Global.h>

class AM_AppLnk;

class AM_QtPackageManager
{
public:
	int MessageBox(QPixmap const&, QString const&, QString const& message, QString const& left_button, QString const& mid_button, QString const& right_button);
	void modifyDatabase(QString const&, QString const&, QString&);
	void uninstallModifyDatabase(AM_AppLnk const&);
	void install(QString const& file, AM_Global::Device=AM_Global::Card1); //AM_Global::Device does not affect
	void uninstall(AM_AppLnk const&);
	AM_QtPackageManager();
	~AM_QtPackageManager();

private:
	char x[58];
	
};

#endif //AM_QTPACKAGEMANAGER_H

