//generated by genheader.sh write by wangbin
/********************************************************
**libezxappbase.so.1.0.0
**Tue Aug 24 10:20:13     2010
*************************************************************/
#ifndef EZXCALIBRATEDTOUCHPANEL_H
#define EZXCALIBRATEDTOUCHPANEL_H

#include <qwidget.h>

class QWSPointerCalibrationData;
class TP_Calibration_Parameter_T;

class EzxCalibratedTouchPanel :public QWidget
{
	Q_OBJECT
public:
	EzxCalibratedTouchPanel();
	~EzxCalibratedTouchPanel();
	
	void CalculatePoint(QPoint&, TP_Calibration_Parameter_T&);
	void getCalibration(QWSPointerCalibrationData*);
	void getCalibration(TP_Calibration_Parameter_T*);
	void readCalibration();
	void clearCalibration();
	void writeCalibration();

signals:
	void mouseEventActivated();
	
public slots:
	void calibrate(QWSPointerCalibrationData*);
	void transform(QPoint const&);

};

#endif //EZXCALIBRATEDTOUCHPANEL_H

