//generated by genheader.sh write by wangbin

#ifndef UTIL_RES_H
#define UTIL_RES_H

class UTIL_Res
{
public:
	uint bigToLittle(uint);
	void createID(QString);
	bool hashVal(QString);
	
};

#endif //UTIL_RES_H

