//generated by genheader.sh write by wangbin
/********************************************************
**libezxappsdk.so.1.0.0
**2010年 07月 07日 星期三 10:44:16 CST
*************************************************************/
#ifndef MSGAPI_SMS_H
#define MSGAPI_SMS_H
#include <qobject.h>

class MSGAPI_SMS_Listener;
class MSGAPI_OUTGO_SMS_S;
class MSGAPI_INCOME_SMS_S;
class MSGAPI_MSG_RECORD_ID;

class MSGAPI_SMS :public QObject
{
	Q_OBJECT
public:
	MSGAPI_SMS(QObject* parent=0, char const* name=0, MSGAPI_SMS_Listener* listener=0);
	virtual ~MSGAPI_SMS();
	
	void gotoMessagingCenterHomeScreen();
	void showMsg(MSGAPI_INCOME_SMS_S const&, MSGAPI_MSG_RECORD_ID const&);
	void deleteMsg(unsigned int*, MSGAPI_MSG_RECORD_ID const&);
	void setMsgAsRead(unsigned int*, MSGAPI_MSG_RECORD_ID const&);
	
	void composeMsg(unsigned int*, MSGAPI_OUTGO_SMS_S const&);
	void send(unsigned int*, MSGAPI_OUTGO_SMS_S const&);
	void send(unsigned int*, MSGAPI_OUTGO_SMS_S const&, MSGAPI_MSG_RECORD_ID const&);
	
	void saveToDraft(unsigned int*, MSGAPI_OUTGO_SMS_S const&);
	void saveToDraft(unsigned int*, MSGAPI_OUTGO_SMS_S const&, MSGAPI_MSG_RECORD_ID const&);
	void rspnsOfSaveToDraft(unsigned int, int, MSGAPI_MSG_RECORD_ID const&);
	void getTextTemplate(unsigned int*);
	void rspnsOfGetTextTemplate(unsigned int, int, QStringList const&);
	void sendMsgWithResult(unsigned int*, MSGAPI_OUTGO_SMS_S const&);
	void rspnsOfSendMsgWithResult(unsigned int, int);
	void getLatestSmsInDraft(unsigned int*);
	void rspnsOfGetLatestSmsInDraft(unsigned int, int, MSGAPI_OUTGO_SMS_S const&, MSGAPI_MSG_RECORD_ID const&);
	
	int indOfIncomingMsg(MSGAPI_INCOME_SMS_S const&, MSGAPI_MSG_RECORD_ID const&);
	void enableInterceptCheck(bool);
	void notifyInterceptCheckResult(MSGAPI_MSG_RECORD_ID const&, bool);
	void errcodeSendMsgToServer(QCString const&, QArray<char> const&);
	
	bool connectionIsOK() const;
	bool interceptCheckIsEnabled() const;

	MSGAPI_SMS_Listener* listener() const;
signals:	
	void onReceivePeerMsg(QCString const&, QArray<char> const&);
	void onReceiveBroadcastingMsg(QCString const&, QArray<char> const&);
	void onListenerDestroyed(MSGAPI_SMS_Listener*);	
	
private:
	MSGAPI_SMS_Listener* m_listener;	
	
};

#endif //MSGAPI_SMS_H

