//generated by genheader.sh write by wangbin
/********************************************************
**libezxappsdk.so.1.0.0
**2010年 07月 07日 星期三 10:44:16 CST
*************************************************************/
#ifndef MSGAPI_SMS_LISTENER_H
#define MSGAPI_SMS_LISTENER_H

class MSGAPI_SMS;

class MSGAPI_SMS_Listener
{
public:
	MSGAPI_SMS_Listener();
	virtual ~MSGAPI_SMS_Listener();
	
	void setMsgapiSms(MSGAPI_SMS*);

private:
	MSGAPI_SMS* m_msgApiSms;
};

#endif //MSGAPI_SMS_LISTENER_H

