//generated by genheader.sh write by wangbin
/********************************************************
**libezxappsdk.so.1.0.0
**2010年 07月 07日 星期三 10:44:16 CST
*************************************************************/
#ifndef MSGCTR_ENG_CLIENTVIAIPCCOPCHNL_H
#define MSGCTR_ENG_CLIENTVIAIPCCOPCHNL_H
#include <MSGAPI_SMS.h>

class MSGCTR_ENG_ClientViaIpcCopchnl :public MSGAPI_SMS
{
	Q_OBJECT
public:
	MSGCTR_ENG_ClientViaIpcCopchnl(QString const&, QString const&, QString const&, QObject*, char const*, MSGCTR_ENG_ClientViaIpcCopchnlListener*);
	virtual ~MSGCTR_ENG_ClientViaIpcCopchnl();
	
signals:	
	void onReceivePeerMsg(QCString const&, QArray<char> const&);
	void onReceiveBroadcastingMsg(QCString const&, QArray<char> const&);
	void connectionToServerIsOK();
	void serverCopchnlIsRegistered();
	
public slots:
	void slotOfPeerMsg(QCString const&, QArray<char> const&);
	void slotOfBroadcastingMsg(QCString const&, QArray<char> const&);
	void bSendMsgToServer(QCString const&, QArray<char> const&);	

};

#endif //MSGCTR_ENG_CLIENTVIAIPCCOPCHNL_H

