/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_ARM 1
#undef  CONFIG_EISA
#undef  CONFIG_SBUS
#undef  CONFIG_MCA
#define CONFIG_UID16 1
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#undef  CONFIG_RWSEM_XCHGADD_ALGORITHM
#undef  CONFIG_GENERIC_BUST_SPINLOCK
#undef  CONFIG_GENERIC_ISA_DMA

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#undef  CONFIG_OBSOLETE

/*
 * Loadable module support
 */
#undef  CONFIG_MODULES
#undef  CONFIG_MODVERSIONS
#undef  CONFIG_KMOD

/*
 * System Type
 */
#undef  CONFIG_ARCH_ANAKIN
#undef  CONFIG_ARCH_ARCA5K
#undef  CONFIG_ARCH_CLPS7500
#undef  CONFIG_ARCH_CLPS711X
#undef  CONFIG_ARCH_CO285
#undef  CONFIG_ARCH_EBSA110
#undef  CONFIG_ARCH_CAMELOT
#define CONFIG_ARCH_FOOTBRIDGE 1
#undef  CONFIG_ARCH_INTEGRATOR
#undef  CONFIG_ARCH_OMAHA
#undef  CONFIG_ARCH_L7200
#undef  CONFIG_ARCH_MX1ADS
#undef  CONFIG_ARCH_RPC
#undef  CONFIG_ARCH_RISCSTATION
#undef  CONFIG_ARCH_SA1100
#undef  CONFIG_ARCH_SHARK
#undef  CONFIG_ARCH_AT91RM9200

/*
 * Archimedes/A5000 Implementations
 */

/*
 * Archimedes/A5000 Implementations (select only ONE)
 */
#undef  CONFIG_ARCH_ARC
#undef  CONFIG_ARCH_A5K

/*
 * Footbridge Implementations
 */
#undef  CONFIG_ARCH_CATS
#undef  CONFIG_ARCH_PERSONAL_SERVER
#undef  CONFIG_ARCH_EBSA285_ADDIN
#undef  CONFIG_ARCH_EBSA285_HOST
#define CONFIG_ARCH_NETWINDER 1

/*
 * SA11x0 Implementations
 */
#undef  CONFIG_SA1100_ACCELENT
#undef  CONFIG_SA1100_ASSABET
#undef  CONFIG_ASSABET_NEPONSET
#undef  CONFIG_SA1100_ADSAGC
#undef  CONFIG_SA1100_ADSBITSY
#undef  CONFIG_SA1100_ADSBITSYPLUS
#undef  CONFIG_SA1100_BRUTUS
#undef  CONFIG_SA1100_CEP
#undef  CONFIG_SA1100_CERF
#undef  CONFIG_SA1100_H3100
#undef  CONFIG_SA1100_H3600
#undef  CONFIG_SA1100_H3800
#undef  CONFIG_SA1100_H3XXX
#undef  CONFIG_H3600_SLEEVE
#undef  CONFIG_SA1100_EXTENEX1
#undef  CONFIG_SA1100_FLEXANET
#undef  CONFIG_SA1100_FREEBIRD
#undef  CONFIG_SA1100_FRODO
#undef  CONFIG_SA1100_GRAPHICSCLIENT
#undef  CONFIG_SA1100_GRAPHICSMASTER
#undef  CONFIG_SA1100_HACKKIT
#undef  CONFIG_SA1100_BADGE4
#undef  CONFIG_SA1100_JORNADA720
#undef  CONFIG_SA1100_HUW_WEBPANEL
#undef  CONFIG_SA1100_ITSY
#undef  CONFIG_SA1100_LART
#undef  CONFIG_SA1100_NANOENGINE
#undef  CONFIG_SA1100_OMNIMETER
#undef  CONFIG_SA1100_PANGOLIN
#undef  CONFIG_SA1100_PLEB
#undef  CONFIG_SA1100_PT_SYSTEM3
#undef  CONFIG_SA1100_SHANNON
#undef  CONFIG_SA1100_SHERMAN
#undef  CONFIG_SA1100_SIMPAD
#undef  CONFIG_SA1100_SIMPUTER
#undef  CONFIG_SA1100_PFS168
#undef  CONFIG_SA1100_VICTOR
#undef  CONFIG_SA1100_XP860
#undef  CONFIG_SA1100_YOPY
#undef  CONFIG_SA1100_USB
#undef  CONFIG_SA1100_USB_NETLINK
#undef  CONFIG_SA1100_USB_CHAR
#undef  CONFIG_SA1100_SSP

/*
 * AT91RM9200 Implementations
 */
#undef  CONFIG_ARCH_AT91RM9200DK

/*
 * CLPS711X/EP721X Implementations
 */
#undef  CONFIG_ARCH_AUTCPU12
#undef  CONFIG_ARCH_CDB89712
#undef  CONFIG_ARCH_CLEP7312
#undef  CONFIG_ARCH_EDB7211
#undef  CONFIG_ARCH_FORTUNET
#undef  CONFIG_ARCH_GUIDEA07
#undef  CONFIG_ARCH_P720T
#undef  CONFIG_ARCH_EP7211
#undef  CONFIG_ARCH_EP7212
#undef  CONFIG_ARCH_ACORN
#define CONFIG_FOOTBRIDGE 1
#define CONFIG_FOOTBRIDGE_HOST 1
#undef  CONFIG_FOOTBRIDGE_ADDIN

/*
 * Processor Type
 */
#define CONFIG_CPU_32 1
#undef  CONFIG_CPU_26
#undef  CONFIG_CPU_ARM610
#undef  CONFIG_CPU_ARM710
#undef  CONFIG_CPU_ARM720T
#undef  CONFIG_CPU_ARM920T
#undef  CONFIG_CPU_ARM922T
#undef  CONFIG_PLD
#undef  CONFIG_CPU_ARM926T
#undef  CONFIG_CPU_ARM1020
#undef  CONFIG_CPU_ARM1026
#define CONFIG_CPU_SA110 1
#undef  CONFIG_CPU_SA1100
#undef  CONFIG_CPU_32v3
#define CONFIG_CPU_32v4 1

/*
 * Processor Features
 */
#undef  CONFIG_DISCONTIGMEM

/*
 * General setup
 */
#define CONFIG_PCI 1
#define CONFIG_ISA 1
#define CONFIG_ISA_DMA 1
#undef  CONFIG_ZBOOT_ROM
#define CONFIG_ZBOOT_ROM_TEXT 0x0
#define CONFIG_ZBOOT_ROM_BSS 0x0
#define CONFIG_PCI_NAMES 1
#undef  CONFIG_HOTPLUG
#undef  CONFIG_PCMCIA
#define CONFIG_NET 1
#define CONFIG_SYSVIPC 1
#undef  CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1

/*
 * At least one math emulation must be selected
 */
#define CONFIG_FPE_NWFPE 1
#undef  CONFIG_FPE_NWFPE_XP
#undef  CONFIG_FPE_FASTFPE
#define CONFIG_KCORE_ELF 1
#undef  CONFIG_KCORE_AOUT
#define CONFIG_BINFMT_AOUT 1
#define CONFIG_BINFMT_ELF 1
#undef  CONFIG_BINFMT_MISC
#undef  CONFIG_PM
#undef  CONFIG_ARTHUR
#define CONFIG_CMDLINE "root=0x301"
#define CONFIG_LEDS 1
#undef  CONFIG_LEDS_TIMER
#define CONFIG_LEDS_CPU 1
#define CONFIG_ALIGNMENT_TRAP 1

/*
 * Parallel port support
 */
#define CONFIG_PARPORT 1
#define CONFIG_PARPORT_PC 1
#define CONFIG_PARPORT_PC_CML1 1
#undef  CONFIG_PARPORT_SERIAL
#undef  CONFIG_PARPORT_PC_FIFO
#define CONFIG_PARPORT_PC_SUPERIO 1
#undef  CONFIG_PARPORT_PC_PCMCIA
#undef  CONFIG_PARPORT_ARC
#undef  CONFIG_PARPORT_AMIGA
#undef  CONFIG_PARPORT_MFC3
#undef  CONFIG_PARPORT_ATARI
#undef  CONFIG_PARPORT_GSC
#undef  CONFIG_PARPORT_SUNBPP
#undef  CONFIG_PARPORT_IP22
#undef  CONFIG_PARPORT_OTHER
#undef  CONFIG_PARPORT_1284

/*
 * Memory Technology Devices (MTD)
 */
#undef  CONFIG_MTD

/*
 * Plug and Play configuration
 */
#undef  CONFIG_PNP
#undef  CONFIG_ISAPNP

/*
 * Block devices
 */
#undef  CONFIG_BLK_DEV_FD
#undef  CONFIG_BLK_DEV_XD
#undef  CONFIG_PARIDE
#undef  CONFIG_BLK_CPQ_DA
#undef  CONFIG_BLK_CPQ_CISS_DA
#undef  CONFIG_CISS_SCSI_TAPE
#undef  CONFIG_CISS_MONITOR_THREAD
#undef  CONFIG_BLK_DEV_DAC960
#undef  CONFIG_BLK_DEV_UMEM
#define CONFIG_BLK_DEV_LOOP 1
#undef  CONFIG_BLK_DEV_NBD
#undef  CONFIG_BLK_DEV_RAM
#undef  CONFIG_BLK_DEV_INITRD
#undef  CONFIG_BLK_STATS

/*
 * Multi-device support (RAID and LVM)
 */
#undef  CONFIG_MD
#undef  CONFIG_BLK_DEV_MD
#undef  CONFIG_MD_LINEAR
#undef  CONFIG_MD_RAID0
#undef  CONFIG_MD_RAID1
#undef  CONFIG_MD_RAID5
#undef  CONFIG_MD_MULTIPATH
#undef  CONFIG_BLK_DEV_LVM

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#undef  CONFIG_PACKET_MMAP
#define CONFIG_NETLINK_DEV 1
#define CONFIG_NETFILTER 1
#undef  CONFIG_NETFILTER_DEBUG
#undef  CONFIG_FILTER
#define CONFIG_UNIX 1
#define CONFIG_INET 1
#undef  CONFIG_IP_MULTICAST
#undef  CONFIG_IP_ADVANCED_ROUTER
#define CONFIG_IP_PNP 1
#define CONFIG_IP_PNP_DHCP 1
#define CONFIG_IP_PNP_BOOTP 1
#define CONFIG_IP_PNP_RARP 1
#undef  CONFIG_NET_IPIP
#undef  CONFIG_NET_IPGRE
#undef  CONFIG_ARPD
#undef  CONFIG_INET_ECN
#undef  CONFIG_SYN_COOKIES

/*
 *   IP: Netfilter Configuration
 */
#define CONFIG_IP_NF_CONNTRACK 1
#define CONFIG_IP_NF_FTP 1
#undef  CONFIG_IP_NF_AMANDA
#undef  CONFIG_IP_NF_TFTP
#undef  CONFIG_IP_NF_IRC
#define CONFIG_IP_NF_QUEUE 1
#define CONFIG_IP_NF_IPTABLES 1
#undef  CONFIG_IP_NF_MATCH_LIMIT
#undef  CONFIG_IP_NF_MATCH_MAC
#undef  CONFIG_IP_NF_MATCH_PKTTYPE
#undef  CONFIG_IP_NF_MATCH_MARK
#undef  CONFIG_IP_NF_MATCH_MULTIPORT
#undef  CONFIG_IP_NF_MATCH_TOS
#undef  CONFIG_IP_NF_MATCH_RECENT
#undef  CONFIG_IP_NF_MATCH_ECN
#undef  CONFIG_IP_NF_MATCH_DSCP
#undef  CONFIG_IP_NF_MATCH_AH_ESP
#undef  CONFIG_IP_NF_MATCH_LENGTH
#undef  CONFIG_IP_NF_MATCH_TTL
#undef  CONFIG_IP_NF_MATCH_TCPMSS
#undef  CONFIG_IP_NF_MATCH_HELPER
#undef  CONFIG_IP_NF_MATCH_STATE
#undef  CONFIG_IP_NF_MATCH_CONNTRACK
#undef  CONFIG_IP_NF_MATCH_UNCLEAN
#undef  CONFIG_IP_NF_MATCH_OWNER
#undef  CONFIG_IP_NF_FILTER
#undef  CONFIG_IP_NF_NAT
#undef  CONFIG_IP_NF_MANGLE
#undef  CONFIG_IP_NF_TARGET_LOG
#undef  CONFIG_IP_NF_TARGET_ULOG
#undef  CONFIG_IP_NF_TARGET_TCPMSS
#undef  CONFIG_IP_NF_ARPTABLES

/*
 *   IP: Virtual Server Configuration
 */
#undef  CONFIG_IP_VS
#undef  CONFIG_IPV6
#undef  CONFIG_KHTTPD

/*
 *    SCTP Configuration (EXPERIMENTAL)
 */
#undef  CONFIG_IP_SCTP
#undef  CONFIG_ATM
#undef  CONFIG_VLAN_8021Q

/*
 *  
 */
#undef  CONFIG_IPX
#undef  CONFIG_ATALK

/*
 * Appletalk devices
 */
#undef  CONFIG_DEV_APPLETALK
#undef  CONFIG_DECNET
#undef  CONFIG_BRIDGE
#undef  CONFIG_X25
#undef  CONFIG_LAPB
#undef  CONFIG_LLC
#undef  CONFIG_NET_DIVERT
#undef  CONFIG_ECONET
#undef  CONFIG_WAN_ROUTER
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_NET_HW_FLOWCONTROL

/*
 * QoS and/or fair queueing
 */
#undef  CONFIG_NET_SCHED

/*
 * Network testing
 */
#undef  CONFIG_NET_PKTGEN

/*
 * Network device support
 */
#define CONFIG_NETDEVICES 1

/*
 * ARCnet devices
 */
#undef  CONFIG_ARCNET
#undef  CONFIG_DUMMY
#undef  CONFIG_BONDING
#undef  CONFIG_EQUALIZER
#undef  CONFIG_TUN
#undef  CONFIG_ETHERTAP

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#undef  CONFIG_ARM_AM79C961A
#undef  CONFIG_ARM_CIRRUS
#undef  CONFIG_SUNLANCE
#undef  CONFIG_HAPPYMEAL
#undef  CONFIG_SUNBMAC
#undef  CONFIG_SUNQE
#undef  CONFIG_SUNGEM
#undef  CONFIG_NET_VENDOR_3COM
#undef  CONFIG_LANCE
#undef  CONFIG_NET_VENDOR_SMC
#undef  CONFIG_NET_VENDOR_RACAL
#undef  CONFIG_AT1700
#undef  CONFIG_DEPCA
#undef  CONFIG_HP100
#undef  CONFIG_NET_ISA
#define CONFIG_NET_PCI 1
#undef  CONFIG_PCNET32
#undef  CONFIG_AMD8111_ETH
#undef  CONFIG_ADAPTEC_STARFIRE
#undef  CONFIG_AC3200
#undef  CONFIG_APRICOT
#undef  CONFIG_B44
#undef  CONFIG_CS89x0
#define CONFIG_TULIP 1
#undef  CONFIG_TULIP_MWI
#define CONFIG_TULIP_MMIO 1
#undef  CONFIG_DE4X5
#undef  CONFIG_DGRS
#undef  CONFIG_DM9102
#undef  CONFIG_EEPRO100
#undef  CONFIG_EEPRO100_PIO
#undef  CONFIG_E100
#undef  CONFIG_LNE390
#undef  CONFIG_FEALNX
#undef  CONFIG_NATSEMI
#define CONFIG_NE2K_PCI 1
#undef  CONFIG_FORCEDETH
#undef  CONFIG_NE3210
#undef  CONFIG_ES3210
#undef  CONFIG_8139CP
#undef  CONFIG_8139TOO
#undef  CONFIG_8139TOO_PIO
#undef  CONFIG_8139TOO_TUNE_TWISTER
#undef  CONFIG_8139TOO_8129
#undef  CONFIG_8139_OLD_RX_RESET
#undef  CONFIG_SIS900
#undef  CONFIG_EPIC100
#undef  CONFIG_SUNDANCE
#undef  CONFIG_SUNDANCE_MMIO
#undef  CONFIG_TLAN
#undef  CONFIG_VIA_RHINE
#undef  CONFIG_VIA_RHINE_MMIO
#undef  CONFIG_WINBOND_840
#undef  CONFIG_NET_POCKET

/*
 * Ethernet (1000 Mbit)
 */
#undef  CONFIG_ACENIC
#undef  CONFIG_DL2K
#undef  CONFIG_E1000
#undef  CONFIG_MYRI_SBUS
#undef  CONFIG_NS83820
#undef  CONFIG_HAMACHI
#undef  CONFIG_YELLOWFIN
#undef  CONFIG_R8169
#undef  CONFIG_SK98LIN
#undef  CONFIG_TIGON3
#undef  CONFIG_FDDI
#undef  CONFIG_HIPPI
#undef  CONFIG_PLIP
#undef  CONFIG_PPP
#undef  CONFIG_SLIP

/*
 * Wireless LAN (non-hamradio)
 */
#undef  CONFIG_NET_RADIO

/*
 * Token Ring devices
 */
#undef  CONFIG_TR
#undef  CONFIG_NET_FC
#undef  CONFIG_RCPCI
#undef  CONFIG_SHAPER

/*
 * Wan interfaces
 */
#undef  CONFIG_WAN

/*
 * Amateur Radio support
 */
#undef  CONFIG_HAMRADIO

/*
 * IrDA (infrared) support
 */
#undef  CONFIG_IRDA

/*
 * ATA/ATAPI/MFM/RLL support
 */
#define CONFIG_IDE 1

/*
 * IDE, ATA and ATAPI Block devices
 */
#define CONFIG_BLK_DEV_IDE 1

/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef  CONFIG_BLK_DEV_HD_IDE
#undef  CONFIG_BLK_DEV_HD
#define CONFIG_BLK_DEV_IDEDISK 1
#define CONFIG_IDEDISK_MULTI_MODE 1
#undef  CONFIG_IDEDISK_STROKE
#undef  CONFIG_BLK_DEV_IDECS
#undef  CONFIG_BLK_DEV_IDECD
#undef  CONFIG_BLK_DEV_IDETAPE
#undef  CONFIG_BLK_DEV_IDEFLOPPY
#undef  CONFIG_BLK_DEV_IDESCSI
#undef  CONFIG_IDE_TASK_IOCTL

/*
 * IDE chipset support/bugfixes
 */
#undef  CONFIG_BLK_DEV_CMD640
#undef  CONFIG_BLK_DEV_CMD640_ENHANCED
#undef  CONFIG_BLK_DEV_ISAPNP
#define CONFIG_BLK_DEV_IDEPCI 1
#undef  CONFIG_BLK_DEV_GENERIC
#undef  CONFIG_IDEPCI_SHARE_IRQ
#define CONFIG_BLK_DEV_IDEDMA_PCI 1
#undef  CONFIG_BLK_DEV_OFFBOARD
#undef  CONFIG_BLK_DEV_IDEDMA_FORCED
#define CONFIG_IDEDMA_PCI_AUTO 1
#undef  CONFIG_IDEDMA_ONLYDISK
#define CONFIG_BLK_DEV_IDEDMA 1
#undef  CONFIG_IDEDMA_PCI_WIP
#undef  CONFIG_BLK_DEV_ADMA100
#undef  CONFIG_BLK_DEV_AEC62XX
#undef  CONFIG_BLK_DEV_ALI15X3
#undef  CONFIG_WDC_ALI15X3
#undef  CONFIG_BLK_DEV_AMD74XX
#undef  CONFIG_AMD74XX_OVERRIDE
#undef  CONFIG_BLK_DEV_ATIIXP
#undef  CONFIG_BLK_DEV_CMD64X
#undef  CONFIG_BLK_DEV_TRIFLEX
#undef  CONFIG_BLK_DEV_CY82C693
#undef  CONFIG_BLK_DEV_CS5530
#undef  CONFIG_BLK_DEV_HPT34X
#undef  CONFIG_HPT34X_AUTODMA
#undef  CONFIG_BLK_DEV_HPT366
#undef  CONFIG_BLK_DEV_PIIX
#undef  CONFIG_BLK_DEV_NS87415
#undef  CONFIG_BLK_DEV_OPTI621
#undef  CONFIG_BLK_DEV_PDC202XX_OLD
#undef  CONFIG_PDC202XX_BURST
#undef  CONFIG_BLK_DEV_PDC202XX_NEW
#undef  CONFIG_BLK_DEV_RZ1000
#undef  CONFIG_BLK_DEV_SC1200
#undef  CONFIG_BLK_DEV_SVWKS
#undef  CONFIG_BLK_DEV_SIIMAGE
#undef  CONFIG_BLK_DEV_SIS5513
#undef  CONFIG_BLK_DEV_SLC90E66
#undef  CONFIG_BLK_DEV_TRM290
#undef  CONFIG_BLK_DEV_VIA82CXXX
#define CONFIG_BLK_DEV_SL82C105 1
#undef  CONFIG_IDE_CHIPSETS
#define CONFIG_IDEDMA_AUTO 1
#undef  CONFIG_IDEDMA_IVB
#undef  CONFIG_DMA_NONPCI
#undef  CONFIG_BLK_DEV_ATARAID
#undef  CONFIG_BLK_DEV_ATARAID_PDC
#undef  CONFIG_BLK_DEV_ATARAID_HPT
#undef  CONFIG_BLK_DEV_ATARAID_MEDLEY
#undef  CONFIG_BLK_DEV_ATARAID_SII

/*
 * SCSI support
 */
#undef  CONFIG_SCSI

/*
 * IEEE 1394 (FireWire) support (EXPERIMENTAL)
 */
#undef  CONFIG_IEEE1394

/*
 * I2O device support
 */
#undef  CONFIG_I2O
#undef  CONFIG_I2O_PCI
#undef  CONFIG_I2O_BLOCK
#undef  CONFIG_I2O_LAN
#undef  CONFIG_I2O_SCSI
#undef  CONFIG_I2O_PROC

/*
 * ISDN subsystem
 */
#undef  CONFIG_ISDN

/*
 * Input core support
 */
#define CONFIG_INPUT 1
#undef  CONFIG_INPUT_KEYBDEV
#define CONFIG_INPUT_MOUSEDEV 1
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X (1024)
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y (768)
#undef  CONFIG_INPUT_JOYDEV
#undef  CONFIG_INPUT_EVDEV
#define CONFIG_INPUT_UINPUT 1

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#undef  CONFIG_SERIAL
#undef  CONFIG_SERIAL_EXTENDED
#undef  CONFIG_SERIAL_NONSTANDARD
#undef  CONFIG_SERIAL_21285
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_UNIX98_PTY_COUNT (256)
#define CONFIG_PRINTER 1
#undef  CONFIG_LP_CONSOLE
#undef  CONFIG_PPDEV
#undef  CONFIG_TIPAR

/*
 * I2C support
 */
#undef  CONFIG_I2C

/*
 * Mice
 */
#undef  CONFIG_BUSMOUSE
#undef  CONFIG_MOUSE

/*
 * Joysticks
 */
#undef  CONFIG_INPUT_GAMEPORT
#undef  CONFIG_INPUT_NS558
#undef  CONFIG_INPUT_LIGHTNING
#undef  CONFIG_INPUT_PCIGAME
#undef  CONFIG_INPUT_CS461X
#undef  CONFIG_INPUT_EMU10K1
#undef  CONFIG_INPUT_SERIO
#undef  CONFIG_INPUT_SERPORT

/*
 * Joysticks
 */
#undef  CONFIG_INPUT_ANALOG
#undef  CONFIG_INPUT_A3D
#undef  CONFIG_INPUT_ADI
#undef  CONFIG_INPUT_COBRA
#undef  CONFIG_INPUT_GF2K
#undef  CONFIG_INPUT_GRIP
#undef  CONFIG_INPUT_INTERACT
#undef  CONFIG_INPUT_TMDC
#undef  CONFIG_INPUT_SIDEWINDER
#undef  CONFIG_INPUT_IFORCE_USB
#undef  CONFIG_INPUT_IFORCE_232
#undef  CONFIG_INPUT_WARRIOR
#undef  CONFIG_INPUT_MAGELLAN
#undef  CONFIG_INPUT_SPACEORB
#undef  CONFIG_INPUT_SPACEBALL
#undef  CONFIG_INPUT_STINGER
#undef  CONFIG_INPUT_DB9
#undef  CONFIG_INPUT_GAMECON
#undef  CONFIG_INPUT_TURBOGRAFX
#undef  CONFIG_QIC02_TAPE
#undef  CONFIG_IPMI_HANDLER
#undef  CONFIG_IPMI_PANIC_EVENT
#undef  CONFIG_IPMI_DEVICE_INTERFACE
#undef  CONFIG_IPMI_KCS
#undef  CONFIG_IPMI_WATCHDOG

/*
 * Watchdog Cards
 */
#define CONFIG_WATCHDOG 1
#undef  CONFIG_WATCHDOG_NOWAYOUT
#undef  CONFIG_ACQUIRE_WDT
#undef  CONFIG_ADVANTECH_WDT
#undef  CONFIG_ALIM1535_WDT
#undef  CONFIG_ALIM7101_WDT
#undef  CONFIG_SC520_WDT
#undef  CONFIG_PCWATCHDOG
#undef  CONFIG_21285_WATCHDOG
#undef  CONFIG_977_WATCHDOG
#undef  CONFIG_EUROTECH_WDT
#undef  CONFIG_IB700_WDT
#undef  CONFIG_WAFER_WDT
#undef  CONFIG_I810_TCO
#undef  CONFIG_MIXCOMWD
#undef  CONFIG_60XX_WDT
#undef  CONFIG_SC1200_WDT
#undef  CONFIG_SCx200_WDT
#undef  CONFIG_SOFT_WATCHDOG
#undef  CONFIG_W83877F_WDT
#undef  CONFIG_WDT
#undef  CONFIG_WDTPCI
#undef  CONFIG_MACHZ_WDT
#undef  CONFIG_AMD7XX_TCO
#define CONFIG_DS1620 1
#define CONFIG_NWBUTTON 1
#define CONFIG_NWBUTTON_REBOOT 1
#define CONFIG_NWFLASH 1
#undef  CONFIG_SCx200
#undef  CONFIG_SCx200_GPIO
#undef  CONFIG_AMD_PM768
#undef  CONFIG_NVRAM
#define CONFIG_RTC 1
#undef  CONFIG_DTLK
#undef  CONFIG_R3964
#undef  CONFIG_APPLICOM

/*
 * Ftape, the floppy tape device driver
 */
#undef  CONFIG_FTAPE
#undef  CONFIG_AGP

/*
 * Direct Rendering Manager (XFree86 DRI support)
 */
#undef  CONFIG_DRM

/*
 * Multimedia devices
 */
#undef  CONFIG_VIDEO_DEV

/*
 * File systems
 */
#undef  CONFIG_QUOTA
#undef  CONFIG_QFMT_V2
#define CONFIG_AUTOFS_FS 1
#undef  CONFIG_AUTOFS4_FS
#undef  CONFIG_REISERFS_FS
#undef  CONFIG_REISERFS_CHECK
#undef  CONFIG_REISERFS_PROC_INFO
#undef  CONFIG_ADFS_FS
#undef  CONFIG_ADFS_FS_RW
#undef  CONFIG_AFFS_FS
#undef  CONFIG_HFS_FS
#undef  CONFIG_HFSPLUS_FS
#undef  CONFIG_BEFS_FS
#undef  CONFIG_BEFS_DEBUG
#undef  CONFIG_BFS_FS
#undef  CONFIG_EXT3_FS
#undef  CONFIG_JBD
#undef  CONFIG_JBD_DEBUG
#undef  CONFIG_FAT_FS
#undef  CONFIG_MSDOS_FS
#undef  CONFIG_UMSDOS_FS
#undef  CONFIG_VFAT_FS
#undef  CONFIG_EFS_FS
#undef  CONFIG_JFFS_FS
#undef  CONFIG_JFFS2_FS
#undef  CONFIG_CRAMFS
#define CONFIG_TMPFS 1
#define CONFIG_RAMFS 1
#define CONFIG_ISO9660_FS 1
#define CONFIG_JOLIET 1
#undef  CONFIG_ZISOFS
#undef  CONFIG_JFS_FS
#undef  CONFIG_JFS_DEBUG
#undef  CONFIG_JFS_STATISTICS
#undef  CONFIG_MINIX_FS
#undef  CONFIG_VXFS_FS
#undef  CONFIG_NTFS_FS
#undef  CONFIG_NTFS_RW
#undef  CONFIG_HPFS_FS
#define CONFIG_PROC_FS 1
#undef  CONFIG_DEVFS_FS
#undef  CONFIG_DEVFS_MOUNT
#undef  CONFIG_DEVFS_DEBUG
#undef  CONFIG_DEVPTS_FS
#undef  CONFIG_QNX4FS_FS
#undef  CONFIG_QNX4FS_RW
#undef  CONFIG_ROMFS_FS
#define CONFIG_EXT2_FS 1
#undef  CONFIG_SYSV_FS
#undef  CONFIG_UDF_FS
#undef  CONFIG_UDF_RW
#undef  CONFIG_UFS_FS
#undef  CONFIG_UFS_FS_WRITE
#undef  CONFIG_XFS_FS
#undef  CONFIG_XFS_QUOTA
#undef  CONFIG_XFS_RT
#undef  CONFIG_XFS_TRACE
#undef  CONFIG_XFS_DEBUG

/*
 * Network File Systems
 */
#undef  CONFIG_CODA_FS
#undef  CONFIG_INTERMEZZO_FS
#define CONFIG_NFS_FS 1
#define CONFIG_NFS_V3 1
#undef  CONFIG_NFS_DIRECTIO
#define CONFIG_ROOT_NFS 1
#define CONFIG_NFSD 1
#define CONFIG_NFSD_V3 1
#undef  CONFIG_NFSD_TCP
#define CONFIG_SUNRPC 1
#define CONFIG_LOCKD 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_SMB_FS 1
#undef  CONFIG_SMB_NLS_DEFAULT
#undef  CONFIG_SMB_UNIX
#undef  CONFIG_NCP_FS
#undef  CONFIG_NCPFS_PACKET_SIGNING
#undef  CONFIG_NCPFS_IOCTL_LOCKING
#undef  CONFIG_NCPFS_STRONG
#undef  CONFIG_NCPFS_NFS_NS
#undef  CONFIG_NCPFS_OS2_NS
#undef  CONFIG_NCPFS_SMALLDOS
#undef  CONFIG_NCPFS_NLS
#undef  CONFIG_NCPFS_EXTRAS
#undef  CONFIG_ZISOFS_FS

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#undef  CONFIG_ACORN_PARTITION
#undef  CONFIG_OSF_PARTITION
#undef  CONFIG_AMIGA_PARTITION
#undef  CONFIG_ATARI_PARTITION
#undef  CONFIG_MAC_PARTITION
#define CONFIG_MSDOS_PARTITION 1
#undef  CONFIG_BSD_DISKLABEL
#undef  CONFIG_MINIX_SUBPARTITION
#undef  CONFIG_SOLARIS_X86_PARTITION
#undef  CONFIG_UNIXWARE_DISKLABEL
#undef  CONFIG_LDM_PARTITION
#undef  CONFIG_SGI_PARTITION
#undef  CONFIG_ULTRIX_PARTITION
#undef  CONFIG_SUN_PARTITION
#undef  CONFIG_EFI_PARTITION
#define CONFIG_SMB_NLS 1
#define CONFIG_NLS 1

/*
 * Native Language Support
 */
#define CONFIG_NLS_DEFAULT "iso8859-1"
#define CONFIG_NLS_CODEPAGE_437 1
#undef  CONFIG_NLS_CODEPAGE_737
#undef  CONFIG_NLS_CODEPAGE_775
#define CONFIG_NLS_CODEPAGE_850 1
#define CONFIG_NLS_CODEPAGE_852 1
#undef  CONFIG_NLS_CODEPAGE_855
#undef  CONFIG_NLS_CODEPAGE_857
#undef  CONFIG_NLS_CODEPAGE_860
#undef  CONFIG_NLS_CODEPAGE_861
#undef  CONFIG_NLS_CODEPAGE_862
#undef  CONFIG_NLS_CODEPAGE_863
#undef  CONFIG_NLS_CODEPAGE_864
#undef  CONFIG_NLS_CODEPAGE_865
#undef  CONFIG_NLS_CODEPAGE_866
#undef  CONFIG_NLS_CODEPAGE_869
#undef  CONFIG_NLS_CODEPAGE_936
#undef  CONFIG_NLS_CODEPAGE_950
#undef  CONFIG_NLS_CODEPAGE_932
#undef  CONFIG_NLS_CODEPAGE_949
#undef  CONFIG_NLS_CODEPAGE_874
#undef  CONFIG_NLS_ISO8859_8
#undef  CONFIG_NLS_CODEPAGE_1250
#undef  CONFIG_NLS_CODEPAGE_1251
#define CONFIG_NLS_ISO8859_1 1
#define CONFIG_NLS_ISO8859_2 1
#undef  CONFIG_NLS_ISO8859_3
#undef  CONFIG_NLS_ISO8859_4
#undef  CONFIG_NLS_ISO8859_5
#undef  CONFIG_NLS_ISO8859_6
#undef  CONFIG_NLS_ISO8859_7
#undef  CONFIG_NLS_ISO8859_9
#undef  CONFIG_NLS_ISO8859_13
#undef  CONFIG_NLS_ISO8859_14
#define CONFIG_NLS_ISO8859_15 1
#undef  CONFIG_NLS_KOI8_R
#undef  CONFIG_NLS_KOI8_U
#define CONFIG_NLS_UTF8 1

/*
 * Console drivers
 */
#define CONFIG_PC_KEYB 1
#define CONFIG_PC_KEYMAP 1
#define CONFIG_VGA_CONSOLE 1

/*
 * Frame-buffer support
 */
#define CONFIG_FB 1
#define CONFIG_DUMMY_CONSOLE 1
#undef  CONFIG_FB_RIVA
#undef  CONFIG_FB_CLGEN
#undef  CONFIG_FB_PM2
#undef  CONFIG_FB_PM3
#define CONFIG_FB_CYBER2000 1
#undef  CONFIG_FB_MATROX
#undef  CONFIG_FB_ATY
#undef  CONFIG_FB_RADEON
#undef  CONFIG_FB_ATY128
#undef  CONFIG_FB_INTEL
#undef  CONFIG_FB_SIS
#undef  CONFIG_FB_NEOMAGIC
#undef  CONFIG_FB_3DFX
#undef  CONFIG_FB_VOODOO1
#undef  CONFIG_FB_TRIDENT
#undef  CONFIG_FB_IT8181
#undef  CONFIG_FB_VIRTUAL
#undef  CONFIG_FBCON_ADVANCED
#define CONFIG_FBCON_CFB8 1
#define CONFIG_FBCON_CFB16 1
#define CONFIG_FBCON_CFB24 1
#define CONFIG_FBCON_CFB32 1
#undef  CONFIG_FBCON_FONTWIDTH8_ONLY
#undef  CONFIG_FBCON_FONTS
#define CONFIG_FONT_8x8 1
#define CONFIG_FONT_8x16 1

/*
 * Sound
 */
#define CONFIG_SOUND 1
#undef  CONFIG_SOUND_ALI5455
#undef  CONFIG_SOUND_BT878
#undef  CONFIG_SOUND_CMPCI
#undef  CONFIG_SOUND_EMU10K1
#undef  CONFIG_MIDI_EMU10K1
#undef  CONFIG_SOUND_FUSION
#undef  CONFIG_SOUND_CS4281
#undef  CONFIG_SOUND_ES1370
#undef  CONFIG_SOUND_ES1371
#undef  CONFIG_SOUND_ESSSOLO1
#undef  CONFIG_SOUND_MAESTRO
#undef  CONFIG_SOUND_MAESTRO3
#undef  CONFIG_SOUND_FORTE
#undef  CONFIG_SOUND_ICH
#undef  CONFIG_SOUND_RME96XX
#undef  CONFIG_SOUND_SONICVIBES
#undef  CONFIG_SOUND_TRIDENT
#undef  CONFIG_SOUND_MSNDCLAS
#undef  CONFIG_SOUND_MSNDPIN
#undef  CONFIG_SOUND_VIA82CXXX
#undef  CONFIG_MIDI_VIA82CXXX
#define CONFIG_SOUND_OSS 1
#define CONFIG_SOUND_TRACEINIT 1
#define CONFIG_SOUND_DMAP 1
#undef  CONFIG_SOUND_AD1816
#undef  CONFIG_SOUND_AD1889
#undef  CONFIG_SOUND_SGALAXY
#undef  CONFIG_SOUND_ADLIB
#undef  CONFIG_SOUND_ACI_MIXER
#undef  CONFIG_SOUND_CS4232
#undef  CONFIG_SOUND_SSCAPE
#undef  CONFIG_SOUND_GUS
#undef  CONFIG_SOUND_VMIDI
#undef  CONFIG_SOUND_TRIX
#undef  CONFIG_SOUND_MSS
#undef  CONFIG_SOUND_MPU401
#undef  CONFIG_SOUND_NM256
#undef  CONFIG_SOUND_MAD16
#undef  CONFIG_SOUND_PAS
#undef  CONFIG_PAS_JOYSTICK
#undef  CONFIG_SOUND_PSS
#undef  CONFIG_SOUND_SB
#undef  CONFIG_SOUND_AWE32_SYNTH
#undef  CONFIG_SOUND_KAHLUA
#undef  CONFIG_SOUND_MAUI
#define CONFIG_SOUND_YM3812 1
#undef  CONFIG_SOUND_OPL3SA1
#undef  CONFIG_SOUND_OPL3SA2
#undef  CONFIG_SOUND_YMFPCI
#undef  CONFIG_SOUND_YMFPCI_LEGACY
#undef  CONFIG_SOUND_UART6850
#undef  CONFIG_SOUND_AEDSP16
#define CONFIG_SOUND_WAVEARTIST 1
#undef  CONFIG_SOUND_TVMIXER
#undef  CONFIG_SOUND_AD1980
#undef  CONFIG_SOUND_WM97XX

/*
 * Misc devices
 */

/*
 * USB support
 */
#undef  CONFIG_USB

/*
 * Support for USB gadgets
 */
#undef  CONFIG_USB_GADGET

/*
 * Bluetooth support
 */
#undef  CONFIG_BLUEZ

/*
 * Kernel hacking
 */
#define CONFIG_FRAME_POINTER 1
#define CONFIG_DEBUG_USER 1
#undef  CONFIG_DEBUG_INFO
#undef  CONFIG_NO_PGT_CACHE
#define CONFIG_DEBUG_KERNEL 1
#undef  CONFIG_DEBUG_SLAB
#define CONFIG_MAGIC_SYSRQ 1
#undef  CONFIG_DEBUG_SPINLOCK
#undef  CONFIG_DEBUG_WAITQ
#undef  CONFIG_DEBUG_BUGVERBOSE
#undef  CONFIG_DEBUG_ERRORS
#undef  CONFIG_DEBUG_LL
#undef  CONFIG_DEBUG_DC21285_PORT
#undef  CONFIG_DEBUG_CLPS711X_UART2
#define CONFIG_LOG_BUF_SHIFT (14)

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#undef  CONFIG_CRYPTO_HMAC
#undef  CONFIG_CRYPTO_NULL
#undef  CONFIG_CRYPTO_MD4
#define CONFIG_CRYPTO_MD5 1
#undef  CONFIG_CRYPTO_SHA1
#undef  CONFIG_CRYPTO_SHA256
#undef  CONFIG_CRYPTO_SHA512
#define CONFIG_CRYPTO_DES 1
#undef  CONFIG_CRYPTO_BLOWFISH
#undef  CONFIG_CRYPTO_TWOFISH
#undef  CONFIG_CRYPTO_SERPENT
#undef  CONFIG_CRYPTO_AES
#undef  CONFIG_CRYPTO_CAST5
#undef  CONFIG_CRYPTO_CAST6
#undef  CONFIG_CRYPTO_ARC4
#undef  CONFIG_CRYPTO_DEFLATE
#undef  CONFIG_CRYPTO_TEST

/*
 * Library routines
 */
#define CONFIG_CRC32 1
#undef  CONFIG_ZLIB_INFLATE
#undef  CONFIG_ZLIB_DEFLATE
